name: 📚 Documentation
description: Report an issue related to documentation.
labels: ["documentation"]

body:
  - type: markdown
    attributes:
      value: "## 📚 Documentation"

  - type: textarea
    id: issue-description
    attributes:
      label: Description
      description: A clear and concise description of what the issue is.
      placeholder: Enter the issue details here.
    validations:
      required: true

  - type: markdown
    attributes:
      value: "### Have you read the [Code of Conduct](https://github.com/SoftCreatR/php-openai-sdk/blob/main/CODE_OF_CONDUCT.md)?"

  - type: checkboxes
    id: code-of-conduct
    attributes:
      label: Code of Conduct
      description: Please confirm that you have read the Code of Conduct.
      options:
        - label: I have read the Code of Conduct
          required: true
