name: 💡 Feature / Idea
description: Submit a proposal for a new feature.
labels: ["feature"]
body:
  - type: markdown
    attributes:
      value: "## 💡 Feature / Idea"
  - type: textarea
    id: feature-description
    attributes:
      label: "A clear and concise description of what the feature is."
      placeholder: "Describe the feature here..."
    validations:
      required: true
  - type: checkboxes
    id: checked-previous-issues
    attributes:
      label: "Have you spent some time to check if this issue has been raised before?"
      description: "Please check if a similar issue has been raised before."
      options:
        - label: "I have googled for a similar issue or checked our older issues for a similar idea"
          required: true
  - type: checkboxes
    id: read-code-of-conduct
    attributes:
      label: "Have you read the [Code of Conduct](https://github.com/SoftCreatR/php-openai-sdk/blob/main/CODE_OF_CONDUCT.md)?"
      options:
        - label: "I have read the Code of Conduct"
          required: true
  - type: textarea
    id: pitch
    attributes:
      label: "Pitch"
      description: "Please explain why this feature should be implemented and how it would be used. Add examples, if applicable."
      placeholder: "Explain the reasoning behind the feature and provide examples..."
    validations:
      required: true
