name: Validate PR

on:
  pull_request:
    paths:
      - 'composer.json'
      - '**.php'

jobs:
  syntax-check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [ '7.4', '8.0', '8.1', '8.2', '8.3', '8.4' ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Install Composer dependencies
        run: composer install --no-dev

      - name: Check PHP syntax
        run: find {src,tests} -type f -name "*.php" -exec php -l {} \;

  analyze-code:
    needs: syntax-check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: php-cs-fixer, phpstan
          extensions: mbstring

      - name: Install Composer dependencies
        run: composer install

      - name: Run PHP-CS-Fixer
        run: php-cs-fixer fix --dry-run --diff

      - name: Run PHPStan
        run: phpstan analyse src tests

  check-dependencies:
    needs: analyze-code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install Composer dependencies
        run: composer install

      - name: Run security checker
        run: composer require --dev enlightn/security-checker && vendor/bin/security-checker security:check

  run-tests:
    needs: check-dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: pcov
          ini-values: zend.assertions=1

      - name: Install Composer dependencies
        run: composer install

      - name: Run PHPUnit
        run: vendor/bin/phpunit --coverage-clover=coverage.xml

      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: coverage.xml
          fail_ci_if_error: true

      - name: Upload coverage report to Code Climate
        uses: paambaati/codeclimate-action@v5
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageLocations: ${{github.workspace}}/coverage.xml:clover
